name: docker

on:
  push:
    branches-ignore:
      - 'dependabot/*'
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3

    - name: integration-test
      run: ./integration-test.sh

    - name: docker publish
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: minetestmapserver/mapserver
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: true
        cache: true
